'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class EcaiMapping

    '''<summary>
    '''Transaction_Mapping control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Transaction_Mapping As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''Collateral_Mapping control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Collateral_Mapping As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''Bond_Mapping control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Bond_Mapping As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''NON_DVP_Mapping control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NON_DVP_Mapping As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''txtLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLabel As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btn_Sovereign control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_Sovereign As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btn_Coporate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_Coporate As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btn_Specific control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_Specific As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''grdTran control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdTran As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''btn_Mapping control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_Mapping As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''grdTran2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdTran2 As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''txtECAI control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtECAI As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtCustName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCustName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtMenu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMenu As Global.System.Web.UI.WebControls.TextBox
End Class
